# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "903351ff4e5149e9f3c0ca63d618143b"
name = "surebright-test"
handle = "surebright-test"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "surebright-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
